name: gh-issue-diary
description: Save issue comment as diary

inputs:
  github_token:
    description: 'github token.'
    default: '${{ github.token }}'
    required: true
  repository:
    description: 'repository name.'
    default: '${{ github.repository }}'
    required: true
  content_dir:
    description: 'content directory.'
  assign_user:
    description: 'username to assign diary issues.'
  issue_label:
    description: 'label name for diary issue.'
  

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/cache@v3
      with:
        path: ${{ github.action_path }}/node_modules
        key: ${{ runner.os }}-${{ hashFiles('${{ github.action_path }}/package-lock.json') }}
    - name: build
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        npm ci
        npm run build
    - name: run
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        REPOSITORY: ${{ inputs.repository }}
        CONTENT_DIR: ${{ inputs.content_dir }}
        ASSIGN_USER: ${{ inputs.assign_user }}
        ISSUE_LABEL: ${{ inputs.issue_label }}
      shell: bash
      run: |
        node ${{ github.action_path }}/index.js
    - name: auto commit
      shell: bash
      run: |
        if [ "$(git status --porcelain)" ]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add . && git commit --author "$(git show -s --format='%an<%ae>')" -m "Generate diary text" && git push
        fi
